### PR TITLE
Add React 18 support

### PR DESCRIPTION
**Pull request by gaearon**
Basic support to get people unblocked.

Closes https://github.com/enzymejs/react-shallow-renderer/pull/110.
Closes https://github.com/enzymejs/react-shallow-renderer/issues/109.

### CODE REVIEW

**Comment by ljharb** [comment]
Changes look good, but unfortunately CI isn't testing on multiple react versions.

**Review by NMinhNguyen — APPROVED** [review]

**Comment by gaearon** [comment]
I've verified all tests pass with 16 except the ones with new APIs.

**Comment by gaearon** [comment]
I'm not sure what's up with the CI not running. I also don't have merge rights in this repo. Can I have them pls?

**Comment by ljharb** [comment]
You do already, but the branch protections aren't running, it seems. @NMinhNguyen?

**Comment by NMinhNguyen** [comment]
Not sure why CI isn't wired up, but I can see this build failed https://app.circleci.com/pipelines/github/enzymejs/react-shallow-renderer/143/workflows/a58d521f-9141-41af-b11a-282cbf426bab/jobs/140

**Comment by NMinhNguyen** [comment]
@ljharb are you able to follow https://circleci.com/docs/2.0/enable-checks/ to enable GitHub Checks? I'm not an admin, I don't think, so I can't enable it.

**Comment by gaearon** [comment]
I don't have permissions to Organization Settings so I can't follow that guide.

Screenshot 2022-04-06 at 18 39 38

**Comment by gaearon** [comment]
The last build passed. I don't think I can fix CI without more permissions but let's get this released as a minor?

**Comment by gaearon** [comment]
In the interests of getting this out, I plan to publish from my branch locally. Then when CI is fixed, I'll push a version bump to main.

**Comment by NMinhNguyen** [comment]
I propose temporarily disabling status checks if the CircleCI integration isn't fixed in the next, say, 10 minutes. Then we can merge this PR, bump the version on main and npm publish.

**Comment by ljharb** [comment]
I'll take a look at circle right now; @NMinhNguyen, you are a repo admin, but it might take org ownership.

**Comment by ljharb** [comment]
https://app.circleci.com/projects/project-dashboard/github/enzymejs/ should now be set up; let me know if there's something more i need to do.

**Comment by NMinhNguyen** [comment]
@ljharb thanks. I've raised https://github.com/enzymejs/react-shallow-renderer/pull/116 to check whether CI works

**Pull request merged**
